alias duh='du -h --max-depth=1 '
alias gogo='xdg-open '
alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT0| grep -E "state|to\ full|percentage"'
alias astyle='astyle -s2 -xG -S -n -O -o -k3 -H -p'
alias copy='rsync -aP '
alias tolatin='~/estebanizer.py -i '
alias toutf='~/estebanizer.py -i -u '
alias svndiff='svn diff | colordiff'
alias less='less -R'

alias gs='git status '
alias gb='git branch'
alias gd='git diff '
alias ga='git add -u && git commit -m'
alias gc='git checkout'
alias gg='git grep'
alias gbv='git branch --verbose --sort=-committerdate'
